### ISSUE TITLE
can not restart after changing postgresql.conf

### ISSUE THREAD

**Issue by saclin** [powa-team/powa#107]
only thing I should do first is to change postgresql.conf??
after the following change:
shared_preload_libraries = 'pg_pathman,pg_stat_statements' 

**systemctl restart postgresql-10
Job for postgresql-10.service failed because the control process exited with error code. See "systemctl status postgresql-10.service" and "journalctl -xe" for details.**

and it restart successfully after I change it to 
shared_preload_libraries = 'pg_pathman'

thanks in advance.

**Comment by rjuju** [comment]
Hi,  I'm not sure how it's related to powa, but the most likely cause is that you didn't install the contrib package, so pg_stat_statements isn't available.

Can you check if the contrib package is installed, or show the postgres logs related to the startup failure?

**Comment by KewtonV** [comment]
Hi rjuju. 

I have a similar problem. I installed the "dnf install postgresql10 postgresql10-server" in my Fedora 28 using these instructions:
 "https://www.if-not-true-then-false.com/2012/install-postgresql-on-fedora-centos-red-hat-rhel/". 
But when I was "started" with the command "systemctl start postgresql-10.service" the following error occurred:
[root@localhost Kewton]# systemctl start postgresql-10.service

Job for postgresql-10.service failed because the control process exited with error code.
See "systemctl status postgresql-10.service" and "journalctl -xe" for details.

[root@localhost Kewton]# systemctl status postgresql-10.service

postgresql-10.service - PostgreSQL 10 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-10.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-10-27 06:03:55 -03; 1min 9s ago
     Docs: https://www.postgresql.org/docs/10/static/
  Process: 5783 ExecStart=/usr/pgsql-10/bin/postmaster -D ${PGDATA} (code=exited, status=1/FAILURE)
  Process: 5778 ExecStartPre=/usr/pgsql-10/bin/postgresql-10-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 5783 (code=exited, status=1/FAILURE)

out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.140 -03 [5783] LOG:  listening on IPv4 address "0.0.0.0", port 5432
out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.140 -03 [5783] LOG:  listening on IPv6 address "::", port 5432
out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.152 -03 [5783] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.167 -03 [5783] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.193 -03 [5783] LOG:  redirecting log output to logging collector process
out 27 06:03:55 localhost.localdomain postmaster[5783]: 2018-10-27 06:03:55.193 -03 [5783] HINT:  Future log output will appear in directory "log".
out 27 06:03:55 localhost.localdomain systemd[1]: postgresql-10.service: Main process exited, code=exited, status=1/FAILURE
out 27 06:03:55 localhost.localdomain systemd[1]: postgresql-10.service: Killing process 5785 (postmaster) with signal SIGKILL.
out 27 06:03:55 localhost.localdomain systemd[1]: postgresql-10.service: Failed with result 'exit-code'.
out 27 06:03:55 localhost.localdomain systemd[1]: Failed to start PostgreSQL 10 database server.

Can you help me?

**Comment by KewtonV** [comment]
I also installed **postgresql-devel** and **postgresql-contrib**... 
But it's still going on.

**Comment by rjuju** [comment]
@KewtonV I see that you open another dedicated issue, so I'll close this one, having no news from @saclin
