### ISSUE TITLE
POWA on windows

### ISSUE THREAD

**Issue by amirensit** [powa-team/powa#108]
Is it possible to install POWA on windows 10 ?

There is no signes on the documentation.

**Comment by rjuju** [comment]
As far as I know, you should be able to install it on windows.  The problem is to be able to compile the shared library on windows.  I'm not a windows user myself, nor is anyone of the others contributors, so I'm afraid we can't help you on this.


Some time ago @firedeepan was trying to compile powa-archivist on windows (see https://github.com/powa-team/powa/issues/24).  Maybe he's still around and can help.

Otherwise you could try the links I pointed, maybe that would work.

**Comment by rjuju** [comment]
FTR I added a NO_PGXS option in powa-archivist (https://github.com/powa-team/powa-archivist/commit/38c2c8b76135125913e790d4691d6c221aa3987a), so if that was helpful you won't require a local patch anymore.
