### ISSUE TITLE
Demo not working anymore

### ISSUE THREAD

**Issue by wind39** [powa-team/powa#122]
Hi,

Just to notify you that the page demo-powa.anayrat.info now redirects to https://blog.anayrat.info/ .

Regards,

William

**Comment by rjuju** [comment]
Hello,

Thanks a lot for the warning!  @anayrat can you check it?  It also seems that the certificate is outdated.


In the meantime you can use the v4 demo, which is working as expected: https://dev-powa.anayrat.info/

**Comment by wind39** [comment]
Hi @rjuju ,

Thanks for the quick response. I'm playing with the v4 demo now, thanks.

Best regards,

William

**Comment by anayrat** [comment]
Hello,

Yes, I had an issue with the servers hosting v3 and v4 demo. I quickly reinstalled v4 hopefully it will be released soon.
Your are redirected to my blog due to a subdomain catch-all because demo-powa.anayrat.info do not exist anymore.

I highly recommend you to play with v4 which is much more powerful :)

**Comment by rjuju** [comment]
The official demo is now working (and points to the v4 version, will be changed when the v4 is released), so I'm closing this issue.
