### ISSUE TITLE
How to do offline analysis with PoWA data

### ISSUE THREAD

**Issue by Ikrar-k** [powa-team/powa#123]
Hi Julien,

Can we do offline analysis of existing PoWA data without PoWA web.

**Comment by rjuju** [comment]
Hello,

powa-web is only doing SQL queries, so you can certainly get the same level of information (or even more, since we could do many improvements on the displayed data) without using powa-web.

What would be your use case?  For instance if you want better graphing solution, using grafana instead can be achieved for most of the graphs, though I don't know if the more specific parts can be done with it (like the global index suggestion).

A good way to start working on your own needs would be to activate all queries ran on the powa database, so you get the general idea of how powa-web is retrieving the data, and then modify them to suit your needs.

**Comment by Ikrar-k** [comment]
Hi Julien,

Thanks for the information. We are having Grafana for monitoring and management is not happy to use another Web UI. So we are looking to analysis data in report format. Is there a way which can give us last an hour records to go through performance of a database.

**Comment by rjuju** [comment]
I can understand, but unfortunately I'm not knowledgeable enough with grafana to provide a fully fledged dashboard that would more or less mimic what powa-web is doing (first thing I would be stuck on would be to generate different queries and metrics depending on what is installed on the remote server).

As I said, you could however build your own dashboard easily that would correspond to what you have installed by logging all the queries and adapting the varying part with grafana variables and macros (for instance https://grafana.com/docs/reference/templating/#time-range-variables or https://grafana.com/docs/features/datasources/postgres/#macros to handle the time interval)

**Comment by Ikrar-k** [comment]
HI Julien,

Thank You for the information. This can be closed.
