### ISSUE TITLE
Should we take into account pg_qualstats.sample_rate when setting pg_qualstats.max? 

### ISSUE THREAD

**Issue by yhuelf** [powa-team/powa#157]
cf https://github.com/powa-team/powa/blob/master/docs/components/stats_extensions/pg_qualstats.rst#configuration

> else it should be roughly equal to the number of queries executed during powa.frequency interval of time.

should it be powa.frequency * pg_qualstats.sample_rate ?

**Comment by yhuelf** [comment]
Also, what happens exactly if the max is set too low? Are the least frequent quals removed, like in pg_stat_statements?

And what is the impact of setting the max too high?

**Comment by rjuju** [comment]
`pg_qualstats.sample_rate` and `setting pg_qualstats.max` are for different purpose.  `sample_rate` is there purely for performance reason, as inspecting the quals is quite costly.  If you don't sample the queries (so configure it to 1), you can get dramatic slowdown if you have a busy environment with somewhat complex expressions in your quals.

`max` is only there to be able to mitigate the memory usage vs. how much you can actually sample.

So both should be configured separately, although obviously having a sample_rate to 1 and a max very low can seem incompatible.  Note that if you have OLAP only workload, it could totally be a reasonable configuration.

> Also, what happens exactly if the max is set too low? Are the least frequent quals removed, like in pg_stat_statements?

Yes, pg_qualstats has the same approach for counter eviction (based on usage) and setting the max too low can lead to sampled quals being evicted.  Note that however powa will reset the quals for every snapshot, in order to limit the sample size.  So if you use pg_qualstats with powa that's something to keep in mind.

> And what is the impact of setting the max too high?

higher memory usage on the postgres server, and possibly higher disk usage for powa or other tool saving those metrics.
