### ISSUE TITLE
graph wal_bytes?

### ISSUE THREAD

**Issue by stelb** [powa-team/powa#165]
Hello,
I am currently trying to identify who/which statement is creating the current amount of wal, pg_stat_statements track this, but a graph would be handy, can this be implemented?

Regards

Stefan

**Comment by rjuju** [comment]
Hi,

It should already be the case since version 4.1.0:

* added in powa-archivist as of https://github.com/powa-team/powa-archivist/commit/62db048e409da6e9c57268f17407d5e75ff8c558
* added graphs in powa-web as of https://github.com/powa-team/powa-web/commit/94aa5fb2de7e1120951a7dc411e7991f72f2fea6

The WAL info should be available in graphs and charts for the server, per-database and per-query.

**Comment by stelb** [comment]
Oops, ok, I can see wal_bytes attribute in powa_statements_history_current now, I see it in powa-web source, but not in webui.

**Comment by stelb** [comment]
searching in powa-web source I found this:
```
..
        if pgss18:
            # Add WALs graphs
..
```

**Comment by stelb** [comment]
OK, i forgot to upgrade the extensions in powa database. It's working now.
Thank you!

**Comment by rjuju** [comment]
Great news, thanks a lot for the confirmation!
