### ISSUE TITLE
Corruption after pg_upgradecluster --link?

### ISSUE THREAD

**Issue by seqizz** [powa-team/powa#176]
Hi :wave: 

After postgresql 13>15 switch on the DB, powa database breaks with e.g.:
```
vacuumdb: error: processing of database "powa" failed: ERROR:  MultiXactId 660863 has not been created yet -- apparent wraparound
CONTEXT:  while scanning block 0 offset 3 of relation "public.powa_snapshot_metas"
...  (also)
powa=# select * from powa_snapshot_metas ;
ERROR:  MultiXactId 667650 has not been created yet -- apparent wraparound
```

Saw this on multiple hosts so far. I can do select/reindex/vacuum on powa DB (and on the mentioned table) on v13, but after using pg_upgradecluster with --link option, that table seems to be breaking consistently.

Sorry if I missed something in the documentation. Do we have something which prevents this on powa side? Or postgres upgrade not supported already so we have to re-install powa after major upgrades?

**Comment by rjuju** [comment]
Hi,

This is unfortunately known issue.  Basically, during the upgrade pg_upgrade will start and stop the clusters, but won't prevent background worker from being launched or any write activity from happening.  If some write activity happens during that time, the upgraded cluster will be corrupted.

And unfortunately there's nothing that powa, or any other third-party background worker, can do to prevent it.  As a reference, you can follow the latest discussion about that issue from a few years ago at https://www.postgresql.org/message-id/flat/20210121152357.s6eflhqyh4g5e6dv%40dalibo.com.  No agreement was reached despite more than a year of discussions, so the issue is still open.

The only way that you can prevent that is to manually remove powa (and possibly other third party module if they also do some writes) from shared_preload_libraries before doing the upgrade, and putting it back afterwards on the upgraded cluster.

Note that in case of powa, the corruption should be contained in the powa database (and in the objects created by powa), so the rest of your data should be totally fine.  You can easily recover from that situation by dropping the powa database and recreating afterwards if you still want to use powa (dropping and recreating the extension might work too, but dropping the whole database should be safer).  You will lose the existing metrics, but powa isn't meant to store a long interval of data anyway.

I realize that I didn't document that postgres bug, I will take care of that shortly.

**Comment by seqizz** [comment]
💡Oh thanks for the explanation, this is indeed looks like a postgresql bug.

> I thought if I change the frequency to -1 it might be ok but realized too late this is about the powa db itself :)

Feel free to close after documenting I guess, since we should do a workaround anyway.

**Comment by rjuju** [comment]
Ok!

This is now documented at https://powa.readthedocs.io/en/latest/components/powa-archivist/installation.html#major-postgresql-upgrade
