### ISSUE TITLE
call pg_wait_sampling_reset_profile() after COPY ( SELECT ?, * FROM public.powa_wait_sampling_src (?)) TO STDOUT;

### ISSUE THREAD

**Issue by jw1u1** [powa-team/powa#178]
to avoid generating temporary files during copy, the profile should be reset after the copy.

**Comment by rjuju** [comment]
Hi,

I'm not sure that I understand your root problem.  Which temporary file are you talking about, is it one that's generated by postgres when calling `pg_wait_sampling_profile` because there are a lot of rows, or the temporary file used to implement the copy or something else?  Note that we try to avoid having side effect on the monitoring tools, so resetting pg_wait_sampling would break any other tool that relies on the various metrics being accumulated over time.

Note that in general a temporary file shouldn't really be a problem, especially here as there won't be hundreds of thousands of rows.  And if it's problematic the best solution would probably be to reduce the snapshot frequency as a lot of datasources are likely to be way more expensive than this one.

**Comment by jw1u1** [comment]
![pgbadger-powa](https://github.com/powa-team/powa/assets/89261565/9af9de84-7485-4ba4-b426-d6d7ba311661)
this is what i'm talking about.
It's not a problem in general but for our management.
It would be nice to have at least the option to reset the stats after the snapshot is done.

**Comment by rjuju** [comment]
ah I see thanks.

I'm wondering if you disabled the `pg_wait_sampling.wait_pid` option as advised in the documentation (https://powa.readthedocs.io/en/latest/components/stats_extensions/pg_wait_sampling.html#configuration) if you don't rely on it for other applications, maybe that's the reason for the temporary files.

**Comment by jw1u1** [comment]
No,  pg_wait_sampling.wait_pid could be useful in case of an incident.

**Comment by rjuju** [comment]
I'm confused.  If you want to keep the pid in case of an incident, why do you want to trash every single metric at each snapshot?  You will lose much more information in case of an incident.

**Comment by jw1u1** [comment]
i would have to be fast enough to disable the reset.
Best option would be to keep the stats for a configurable time period.

**Comment by rjuju** [comment]
> i would have to be fast enough to disable the reset.

It doesn't seem like a really practical solution.

The big problem is that the UI expects the metrics to monotonous, so doing a reset would just break all the related widgets.  We could of course make the widgets aware that a reset is done each time but then it means that the reset would have to be mandatory for every user, and that's not something we want to do as it means that powa would decide that it's the only user of those metrics.

Unfortunately I don't really see any good solution for you.  That being said, maybe I lack imagination but I can't really see any scenario where you would actually need the profile pid to diagnose an incident.  That would mean that the incident is still happening so you can still get information on either the OS side or postgres.  If the incident is finished, it's quite unlikely that you will have any useful information tied to a specific pid.

**Comment by mbanck-ntap** [comment]
> The big problem is that the UI expects the metrics to monotonous, so doing a reset would just break all the related widgets.

Well, isn't that a more general problem? AFAICT, restarting the server also resets the statistics, so they are already wrong in those cases.

Maybe PoWA could figure out those jumps and work around them?

**Comment by rjuju** [comment]
> Well, isn't that a more general problem? AFAICT, restarting the server also resets the statistics, so they are already wrong in those cases.

Yes pg_wai_sampling trashes the statistics in case of a clean restart, but all the other extensions will serialize them on disk first (except pg_qualstats but this extension is a bit special and we reset the statistics after each snapshot, as there is no way you will get a small amount of entries).

> Maybe PoWA could figure out those jumps and work around them?

That's indeed something we wanted to fix for a long time, although without being a top priority item.

In general it's not really a problem, as you don't restart your server that often, and only one snapshot will look weird in that case (the rest will look normal).  If you have pg_track_settings you will see that those metrics are associated to a restart so that's easy to tell.

But yes it's a bit more problematic for some other cases, namely pg_stat_statements evictions.  Again, it's usually not that much of a problem as if you get regular evictions, pg_stat_statements overhead will become so bad that either you don't care about performance (and therefore glitches in the UI are not a problem) or you will have to get rid of it and powa at the same time.

IIRC @marco44 wanted to work on that, but it will probably have to wait for the performance issue in case of dozens of remote servers being used that happens with the v5.

**Comment by mbanck-ntap** [comment]
> In general it's not really a problem, as you don't restart your server that often, and only one snapshot will look weird in that case (the rest will look normal). 

Right, the snapshots look ok. But I have the feeling (and one of our customers complained about this) that the aggregated "`# of events`" are also wrong if the selected time range spans a restart/reset. I don't have solid proof/a reproducer, but should I open a separate issue for that nevertheless to keep track off?

**Comment by rjuju** [comment]
I see that you already created a new issue, thanks a lot.  Let's keep the discussion there.
