### ISSUE TITLE
No feedback when AJAX calls are made

### ISSUE THREAD

**Issue by ribbles** [powa-team/powa#64]
Anything time an AJAX call is made, the user is left not knowing that anything is happening. Since I am seeing some actions taking 8+ seconds, I am left thinking that there is an issue with powa, or that there is **no data**.

Part of the reason for the slow action responsiveness is the browser is CPU pegged with javascript.

When updating/changing date ranges, the data tables and graphs existing values are not wiped away before making the AJAX call, resulting in further confusion.

**Comment by rdunklau** [comment]
Thank you for this report.

You should see a spinner on each individual widgets whenever an ajax call is made, do you confirm that ? 

If thats the case, I agree that the spinner is less than ideal as a feedback mechanism for queries with a long duration like this, we'll think about how to improve that. Feel free to suggest anything if you have any idea about that.

If thats not the case, then I'll investigate why not.

And lastly: the root cause of the problem is that the http requests are taking too long to complete :) Where are you seeing these > 8s calls ? Or is it the part about CPU usage ?

**Comment by ribbles** [comment]
I do not see a spinner.

The API call is 8 secs. The payload is 190KB. The browser render time is 30+ seconds.

**Comment by rdunklau** [comment]
What browser and OS are you using ? (with the version). What feels like the slowest part of the UI ? (ie, which page / widget) ? A screenshot of the page after it has rendered could also be useful.
